### ISSUE TITLE
wrong instructions for os x build?

### ISSUE THREAD

**Issue by kovasb** [ibcn-cloudlet/dianne#6]
Following the install instructions, I find gcc-5 installed, not gcc-6 as the later instructions assume.

**Comment by sbohez** [comment]
Have you installed gcc using Homebrew? If so, could you check if you have the latest version? If I run `brew info gcc` I get:
`gcc: stable 6.2.0 (bottled), HEAD`
If you get the same output, you can upgrade using `brew upgrade gcc`; if not, you perhaps need to upgrade Homebrew itself?

You could also try to build using gcc-5 instead of gcc-6, normally it should work though I haven't tested this in a while.
